[WIP] Automatic closing of booked coupon
p-society/Online_Rosei pull request #3
Opened 2018-08-30 11:48 UTC by debck

#2

2018-08-31 07:26 UTC, debck commented
@knrt10  is it correct or i have to make changes?

2018-08-31 07:37 UTC, knrt10 commented
Will try locally today.

2018-09-02 21:08 UTC, knrt10 requested changes
@debck please change accordingly

2018-09-02 21:08 UTC, knrt10 commented on src/routes/adminRoutes.ts
> +    cron.schedule('* * * * Sunday', () => {
@debck as the server is hosted on some foreign country so time won't be scheduled as per our IST. So we need to convert it according to IST i.e we can use in UTC format.

So change the code to this after importing **moment**

```const presentDay = moment().utcOffset("+05:30").format("dddd");
    if (presentDay === "Monday") {
      cron.schedule("0 0 0 * * Monday", () => {
        console.log("running a task every Monday");
        Coupon.find({}).then((coupon: any) => {
          if (coupon.length !== 0) {
            Coupon.collection.drop();
            console.log("Database Deleted");
          }
          else {
            console.log("Already deleted database")
          }
        });
      });
    }```

2018-09-04 03:52 UTC, debck commented
@knrt10 made changes ...plz check it

2018-09-04 15:29 UTC, knrt10 approved these changes
@debck cool

2018-09-04 15:29 UTC, merged